name: Uses Examples

on: workflow_dispatch

jobs:
  uses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: run python script
        run: python script.py
